### ISSUE TITLE
[Bug] Create's Engineer's Goggles overlay displayed incorrectly

### ISSUE THREAD

**Issue by dandy-is-lion** [AHilyard/LegendaryTooltips#134] opened 2023-12-15 03:35 UTC
Minecraft 1.20.1
Forge 47.2.0
Legendary Tooltips 1.4.5
Iceberg 1.1.18
Prism 1.0.5
Create 0.5.1.f

No other mods installed. Legendary Tooltips config is default (fiddled with some display configuration with no luck). Resource pack "EclecticTrove-1.20.1-1.3.0" (tried the no-config version, and no resource pack too). [Create](https://modrinth.com/mod/create)'s Engineer's Goggles overlay is displayed when looking at [Create](https://modrinth.com/mod/create)'s contraptions.

![2023-12-14_21 18 19](https://github.com/AHilyard/LegendaryTooltips/assets/125793933/b68587ee-0e9a-4945-b04f-91dad88242bb)

**Comment by AHilyard** [comment] 2023-12-15 19:19
Duplicate of AHilyard/Iceberg#17. Hopefully will be fixed soon by Create (See linked PR).

**Closed by AHilyard** 2023-12-15 19:19 UTC
