### ISSUE TITLE
Custom borders not working

### ISSUE THREAD

**Issue by Spittys** [AHilyard/LegendaryTooltips#31] opened 2022-07-28 01:01 UTC
Hi there! I'm on 1.19 forge and I've set up custom borders with the Eclectic Trove texture pack and it doesnt seem to work. The colors are fine and work as expected, maybe there is a setting that I'm missing? I can send the config file. Thanks!

**Comment by AHilyard** [comment] 2022-08-01 00:12
Thanks for opening this issue, this problem was caused by a breaking change in a recent version of Forge and has been fixed in Legendary Tooltips 1.3.  Enjoy!

**Closed by AHilyard** 2022-08-01 00:12 UTC
