### ISSUE TITLE
Borders not showing up at all

### ISSUE THREAD

**Issue by keepinitreal247** [AHilyard/LegendaryTooltips#66] opened 2023-04-20 00:54 UTC
the borders just aren't showing up for me in 1.18.2 mod version 1.3.1 (forge) they just look like this I removed my shaders and the mods I thought would interfere with it but it still looks like this I'm not getting the 3d render either I also installed Eclectic Trove (Legendary Tooltips) and it still does nothing everything is set to true in the config and I don't have an option to even turn 3d render on in the config iceberg and prism are installed latest version for 1.18.2

https://www.youtube.com/watch?v=nL4mxms4taA

**Comment by AHilyard** [comment] 2023-04-20 21:29
I think this is a duplicate of this issue: #56
I believe it is some conflict with JEI/REI.  Could you comment on that issue with what version of JEI or REI you are using as well as any addons or plugins for those mods?

**Closed by AHilyard** 2023-04-20 21:29 UTC
